#### 1. How to concatenate two numpy arrays column-wise and row-wise?

In [1]:
import numpy as np
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
# Column-wise concatenation
np.concatenate((a, b), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [2]:
# Row-wise concatenation
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### 2. Consider the random number generation functions in NumPy generate a set of random numbers using the function rand.

In [3]:
a = np.random.rand(11)
a

array([0.5799596 , 0.39083748, 0.20309504, 0.2292498 , 0.00949319,
       0.72716739, 0.72605116, 0.30259944, 0.64060687, 0.31069652,
       0.13178224])

#### 3. Create a 3D array of shape 5x3x2 to contain random decimal numbers between 5 and 10.

In [4]:
a = np.random.uniform(5, 10, size = (5,3,2))
a

array([[[7.09862484, 6.04298859],
        [9.37726346, 8.98287299],
        [9.96969384, 8.00106854]],

       [[8.32192173, 5.82315974],
        [7.80124991, 7.04202501],
        [8.38121079, 8.01160008]],

       [[5.04863786, 6.05690706],
        [9.48070109, 7.57601063],
        [6.62721638, 9.38936763]],

       [[8.50435538, 7.57944205],
        [8.57338228, 9.13582888],
        [6.27905386, 7.47760066]],

       [[9.48532807, 7.21490276],
        [9.63340603, 5.23043318],
        [9.28853342, 5.26503057]]])

#### 4. Create a utility function to generate random arrays using def random_array() takes number of elements as one of the argument, and randint() from random library. Note: Do not use numpy function in this.

In [5]:
import random
def random_array(num, limit):
    result = random.sample(range(1,limit), num)
    return result

random_array(7, random.randint(10,100))

[33, 1, 4, 51, 57, 39, 27]

#### 5. Create and Compute median using both Naive method using python only and Numpy function np.median()

In [6]:
# using Python
import statistics
a = [1,2,3,4,5,6,7,8,9]
statistics.median(a)

5

In [7]:
# using Numpy
np.median(a)

5.0

#### 6. Create naive function to compute variance function, mean function using only python.

In [8]:
def naive(a):
    m = statistics.mean(a)
    v = statistics.variance(a)
    result = "Mean = {} and Variance = {}".format(m,v)
    return result

a = [1,2,3,4,5,6,7,8,9]
naive(a)

'Mean = 5 and Variance = 7.5'

#### 7. Convert a 1D array to a 2D array with 2 rows.
    e.g.
    Input Array: ([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    Output: [[0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9]]

In [9]:
a1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
a2 = np.reshape(a1, (2, 5))
print(a2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


#### 8. How to stack two arrays vertically? Stack arrays A and B vertically?

In [10]:
A = np.array([2, 4, 6, 8, 10])
B = np.array([3, 5, 7, 9, 11])
np.vstack((A, B))

array([[ 2,  4,  6,  8, 10],
       [ 3,  5,  7,  9, 11]])

#### 9. Create a function using numpy to get the common items between two python numpy arrays?

In [11]:
def common(a, b):
    result = "Common Items are: {}".format(np.intersect1d(a, b))
    return result

a = np.array([1,2,3,5,7,8,9])
b = np.array([3,4,5,6,7])
print(common(a, b))

Common Items are: [3 5 7]


#### 10. Create a python function to get the positions where elements of two arrays match using Numpy function?

In [12]:
def position(a, b):
    common = np.intersect1d(a,b)
    result = []
    for i in common:
        result.append(a.tolist().index(i))
    return result

a = np.array([1,2,3,5,7,8,9])
b = np.array([1,2,3,4,7])
print(position(a, b))

[0, 1, 2, 4]


#### 11. How to create a 2D array containing random floats between 5 and 10?

In [13]:
a = np.random.uniform(5, 10, size = (2,5))
a

array([[9.3996645 , 9.97199974, 8.08756126, 5.52606345, 6.97549015],
       [9.74363628, 5.92920195, 9.01468139, 7.58728265, 6.07548318]])

#### 12. Extract the text column species from the 1D iris imported using following url np.genfromtxt()
https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv

In [14]:
import pandas as pd
iris_df = pd.read_csv("https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/iris.csv")
display(iris_df)
s = iris_df.species
np.genfromtxt(s, delimiter = " ")

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan, nan, nan, nan, nan, nan, nan])

#### 13. How to Convert the 1D iris to 2D array iris_2d by omitting the species column and dropping first row?

In [15]:
iris_2d = iris_df.iloc[1:,:4]
iris_2d

sepal_length  sepal_width  petal_length  petal_width
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
5             5.4          3.9           1.7          0.4
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[149 rows x 4 columns]

#### 14. How to compute the mean, median, standard deviation of a numpy array on the same iris dataset?

In [16]:
iris_df.agg(['mean', 'median', 'std'])

sepal_length  sepal_width  petal_length  petal_width
mean        5.843333     3.057333      3.758000     1.199333
median      5.800000     3.000000      4.350000     1.300000
std         0.828066     0.435866      1.765298     0.762238

#### 15. How to scale an array so the values range exactly between 0 and 1 using Admission.csv?
https://raw.githubusercontent.com/ammishra08/MachineLearning/master/Datasets/Admission.csv
Change all the values in the range of 0-1.

In [17]:
admission_df = pd.read_csv("E:/Data/Admission.csv")
display(admission_df)

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

#### 16. Compute and Find the number and position of missing values in iris data’s sepal length column.
(And few missing values).

In [18]:
iris_df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

#### 17. Drop rows that contain a missing value from a numpy array created by using iris dataset?
Hint: There is no direct function for this hence, select the rows of Iris dataset that does not have any
NaN value.

In [19]:
iris_df.dropna(how = 'any').shape
iris_df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

#### 18. Sort the Admission dataset array based on TOEFL Score column and GRE Score. Use separate code for both.

In [20]:
print(admission_df)
# Sorting based on TOEFL Score column
admission_df['TOEFL Score'].sort_values()

     Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1    

368     92
28      93
79      93
411     94
347     94
      ... 
81     120
97     120
297    120
143    120
497    120
Name: TOEFL Score, Length: 500, dtype: int64

In [21]:
# Sorting based on GRE Score column
admission_df['GRE Score'].sort_values()

377    290
117    290
168    293
79     294
272    294
      ... 
81     340
84     340
143    340
384    340
429    340
Name: GRE Score, Length: 500, dtype: int64

#### 19. Compute the Euclidean distance between two arrays using Numpy linalg?

In [22]:
a = np.array([4, 5, 2, 7, 3, 8])
b = np.array([2, 6, 3, 4, 1, 5])
np.linalg.norm(a-b)

5.291502622129181

#### 20. Compute and Find the duplicate entries in the given Numpy array and mark them as True. Create 1-D array

In [23]:
def duplicate_entries(arr):
    u = np.unique(arr)
    arr2 = []
    result = []
    for i in arr:
        if i in arr2:
            result.append(True)
        else:
            result.append(i)
        if i not in arr2:
            arr2.append(i)
    return result
a = np.random.randint(1, 7, 10)
print("Input Array:", a)
duplicate_entries(a)

Input Array: [4 1 4 4 4 5 4 1 2 3]


[4, 1, True, True, True, 5, True, True, 2, 3]

#### 21. How to replace all missing values with 0, in a numpy array using Admission.csv and iris.csv?

In [26]:
m = pd.DataFrame(admission_df)
m = admission_df.replace(np.nan,0)
m

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0             1        337          118                  4  4.5   4.5  9.65   
1             2        324          107                  4  4.0   4.5  8.87   
2             3        316          104                  3  3.0   3.5  8.00   
3             4        322          110                  3  3.5   2.5  8.67   
4             5        314          103                  2  2.0   3.0  8.21   
..          ...        ...          ...                ...  ...   ...   ...   
495         496        332          108                  5  4.5   4.0  9.02   
496         497        337          117                  5  5.0   5.0  9.87   
497         498        330          120                  5  4.5   5.0  9.56   
498         499        312          103                  4  4.0   5.0  8.43   
499         500        327          113                  4  4.5   4.5  9.04   

     Research  Chance of Admit   
0           1              0.92  
1           1              0.76  
2           1              0.72  
3           1              0.80  
4           0              0.65  
..        ...               ...  
495         1              0.87  
496         1              0.96  
497         1              0.93  
498         0              0.73  
499         0              0.84  

[500 rows x 9 columns]

In [25]:
m = pd.DataFrame(iris_df)
m = iris_df.replace(np.nan,0)
m

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]